import Foundation

/// 生成"远程 Claude Code 机器"用的 hook 安装 / forward 脚本。
///
/// 部署链：
///   ClaudePet (Mac) ──serves──► GET /install ──curl|bash──► 远程机器
///     远程机器 install 脚本：
///       1. 把 forward 脚本写到 ~/.claude-pet/claude-pet-hook-remote
///       2. 把它注入 ~/.claude/settings.json 的各 hook
///   远程 Claude Code 触发 hook → forward 脚本 → curl POST 到 Mac:54321/event
///                                                带 X-ClaudePet-Token + hostname
enum RemoteHookScript {

    /// 跟 ClaudeHookInstaller.events 保持一致（远程关心哪些事件）。
    private static let events: [String] = [
        "SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse",
        "PostToolUseFailure", "PermissionRequest", "Notification",
        "Stop", "SubagentStart", "SubagentStop", "PreCompact"
    ]

    /// `/install` 端点返回的一整段 shell 脚本。
    ///
    /// 关键技巧：forward 脚本内部已经把 host/port/token 完全替换好，然后整段
    /// base64 编码进 install 脚本。这样 install 不用搞双层 heredoc 转义
    /// （shell 变量 vs 占位符）的噩梦，base64 解码完直接写盘就行。
    static func makeInstallScript(host: String, port: Int, token: String) -> String {
        let forward = makeForwardScript(host: host, port: port, token: token)
        let forwardB64 = Data(forward.utf8).base64EncodedString()
        let eventList = events.map { "'\($0)'" }.joined(separator: ",")

        return """
        #!/usr/bin/env bash
        set -euo pipefail

        DIR="$HOME/.claude-pet"
        mkdir -p "$DIR"
        SCRIPT="$DIR/claude-pet-hook-remote"

        # forward.sh 已经在 Mac 端预渲染完成（host/port/token 替换好），
        # 用 base64 包进来，远程机器解码即可，避免双层 heredoc 转义问题。
        base64 -d > "$SCRIPT" <<'B64'
        \(forwardB64)
        B64
        chmod +x "$SCRIPT"

        SETTINGS="$HOME/.claude/settings.json"
        mkdir -p "$(dirname "$SETTINGS")"
        [ -f "$SETTINGS" ] || echo '{}' > "$SETTINGS"

        # 用 python 改 settings.json —— 远程机器可能没装 jq，python3 macOS/Linux 通用
        python3 - "$SCRIPT" "$SETTINGS" <<'PYEOF'
        import json, sys
        cmd, path = sys.argv[1], sys.argv[2]
        events = [\(eventList)]
        try:
            with open(path) as f:
                data = json.load(f)
        except Exception:
            data = {}
        if not isinstance(data, dict):
            data = {}
        hooks = data.get('hooks') if isinstance(data.get('hooks'), dict) else {}
        for ev in events:
            entries = hooks.get(ev) if isinstance(hooks.get(ev), list) else []
            new = []
            for e in entries:
                inner = e.get('hooks') if isinstance(e, dict) else None
                if not isinstance(inner, list):
                    new.append(e); continue
                # 跳过已存在的远程 forwarder 条目（避免 install 多次累积）
                if not any('claude-pet-hook-remote' in (h.get('command','') if isinstance(h, dict) else '') for h in inner):
                    new.append(e)
            new.append({'hooks': [{'type': 'command', 'command': cmd + ' ' + ev}]})
            hooks[ev] = new
        data['hooks'] = hooks
        with open(path, 'w') as f:
            json.dump(data, f, indent=2)
        PYEOF

        echo ""
        echo "✓ ClaudePet 远程 hook 已安装"
        echo "  ↳ 上报地址  : http://\(host):\(port)/event"
        echo "  ↳ Forwarder : $SCRIPT"
        echo "  ↳ Settings  : $SETTINGS"
        echo ""
        echo "提示：在 Mac 端 ClaudePet 菜单关掉「局域网同步」即停止接收远程 hook"
        echo "      重新生成 token 后请再次跑此 install 命令"
        echo ""
        """
    }

    /// 生成 forward 脚本（远程机器每次 hook 触发都跑它）。
    /// host/port/token 直接插值进去，无 shell 变量代入。
    private static func makeForwardScript(host: String, port: Int, token: String) -> String {
        return """
        #!/usr/bin/env bash
        # ClaudePet remote hook forwarder. Auto-generated by Mac side.
        # 把 Claude hook 转发到 http://\(host):\(port)/event，
        # 自动注入 hostname 让桌宠气泡能区分多机器。
        set +e
        EVENT="${1:-Unknown}"
        PAYLOAD="$(cat)"
        [ -z "$PAYLOAD" ] && PAYLOAD="{}"
        if ! printf '%s' "$PAYLOAD" | python3 -c 'import sys,json; json.load(sys.stdin)' >/dev/null 2>&1; then
          PAYLOAD="{}"
        fi
        HOST_NAME=$(hostname -s 2>/dev/null || hostname || echo unknown)
        # 把 hostname 注入到 payload.data
        PAYLOAD=$(python3 -c "
        import sys, json
        try:
            d = json.loads(sys.argv[1])
            if not isinstance(d, dict): d = {}
        except Exception:
            d = {}
        d['hostname'] = sys.argv[2]
        print(json.dumps(d))
        " "$PAYLOAD" "$HOST_NAME")
        BODY=$(printf '{"event":"%s","data":%s}' "$EVENT" "$PAYLOAD")
        curl -fsS -X POST "http://\(host):\(port)/event" \\
          -H "Content-Type: application/json" \\
          -H "X-ClaudePet-Token: \(token)" \\
          -d "$BODY" \\
          --max-time 1 \\
          >/dev/null 2>&1
        exit 0
        """
    }
}
